bbernhard/signal-cli-rest-api

Dockerfile
This uses mulit-stage build to separate the build phase from
the distribution image and signigicantly reduces images size.
You can find more information on Docker multistage builds here:
https://docs.docker.com/develop/develop-images/multistage-build/
=> build(Dockerfile): reduce image size from 2G GB to ~0.4GB

src/api/api.go
Thanks for creating this awesome project, it's made interacting with `signal-cli` so easy!
For some reason, when I query the receive endpoint, no messages are received. 
However If I pass a longer timeout of 5 seconds than I can receive messages.
I've added a `"timeout"` query param to the receive endpoint to allow for a custom timeout value.
For example:
```shell
http -v GET 'http://localhost:8080/v1/receive/+4912345678?timeout=5'
```
=> Support custom "timeout" option when receiving messages

Dockerfile, docker-compose.yml, src/main.go
Not seeing a `CONTRIBUTING.md` file so I'll do my best to be specific.
Main change: Changes the JRE image to a `Bionic`-specific image.  This change is in `Dockerfile` line 42.
This PR also allows the port to be configured through `docker-compose.yml`.  This means images built using `docker-compose` will use the configured port, but images built using `docker build` will still default to port 8080.  The environment variable definitions required to do this were added to `docker-compose.yml`.  Nothing breaks if the environment variables are omitted - the API just runs on port 8080 like it does currently.
A small change is made to `main.go` to detect the `PORT` environment variable and use it to configure Swagger if it exists, but fallback to `8080` if it does not (like if it is built with …
=> JRE Dependency Fix + Port Configuration

Dockerfile, entrypoint.sh
Hello,
As mentioned in #31, running as non-root is a best practice.
However current users have a mount point for config with files owned by root.
This fix takes care of updating file ownership on startup.
However with this fix the binary signal-cli-rest-api runs as a child of su process.
Even if "it works", I don't know if there are hidden side effects (signal forwarding?)
Proposed roadmap:
1. Deploy this fix
2. Wait for users to move to this version (thus the owner of their config files will be updated when upgrading to this version)
3. Move back to `ENTRYPOINT ["signal-cli-rest-api"]` with `USER signal-api` directive and remove the entrypoint.sh
What is your opinion on this fix proposal?
I open the PR but please do not merge until we are sure that everything works as expected for …
=> Run as non-root user in Docker

Dockerfile
Adds a [healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck).
=> Add healthcheck

doc/EXAMPLES.md, doc/HOMEASSISTANT.md, src/api/api.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/go.mod, src/go.sum
- Added info on captcha verification to examples and home assistant doc.
- Added annotation to register number API so swagger shows info on request body
- Marked request body as not required for Verify Number API since it's optional unless asked for a PIN code
Do I have to do anything to regenerate the Swagger with the new annotations or does Swaggo run automatically? I'm not familiar with it.
=> Add info on captcha verification to doc

Dockerfile
Without the *.tar the tar file is not deleted. This change saves about 20mb of space.
=> Update Dockerfile to reduce container size

Dockerfile
Add architecture specific libsignal_jni.so && libzkgroup.so for GraalVM (e.g. Raspberry 64)
=> Add architecture specific lib's for GraalVM

docker-compose.yml, src/api/api.go, src/client/client.go, src/docs/swagger.json, src/docs/swagger.yaml, src/main.go
Hey, 
I had a look at your reactions branch and I tried to migrate it to the new JSON-RFC standard. Now, signal-cli allows to send reactions to a group and also to remove them so I wanted to build this in as well. What do you think about the proposed API?
For now, I did not write any documentation or even test it (I did not set up Java or Go) but once you are fine with the API design, we can do everything else.
Best!
Update: I changed the optional remove property to a DELETE endpoint
=> Reactions Endpoint Proposal

src/api/api.go, src/client/client.go
Added support for missing send arguments:
- Mentions
- Quote timestamp
- Quote author
- Quote message
- Quote mentions
This is tested locally with `normal` and `json-rpc`.
~I'm not sure if a `v3` is required. If you think not, I can merge it back to `v2`.~ Edit: it is, otherwise clients have no way to know if mentions and quotes are supported or not (and would simply be lost)
WARNING: this my first ever experience w/ Go, please pay extra attention while reviewing.
=> Added support for missing send arguments

README.md
As I am not maintaining/developing my shell client anymore, I‘d like to remove it from the README.
=> Remove shell client from the README

doc/HOMEASSISTANT.md
Adding a description on how signal-cli-rest-api can trigger automations in Home Assistant. (Sending messages to Signal to trigger events)
=> Documentation proposal

src/client/cli.go
Motivation
----------
The way how I fixed this is that both `Stdout` and `Stderr` are responded back to the client (always).
I don't think it's good practice to discard `$stderr` on success and to discard `$stdout` on error.
Let me know what you think. I'm still very new to Golang.
How to test
-----------
1. First of all you must be able to reproduce "CAPTCHA proof required" error (I guess you need to send a lot of messages to the same number)
2. Execute:
```
curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send' \
-d '{"message": "Test via Signal API!", "number": "<SENDER_PHONE_NUMBER>", "recipients": [ "<RECIPIENT_PHONE_NUMBER>" ]}
'
```
3. See in the JSON response:
```
{"error":"Failed to send (some) messages:\n+49176xxxxxxxx: CAPTCHA proof required for …
```
=> fix: include $stdin in server response on error

.gitignore, src/api/api.go, src/client/client.go, src/main.go
Hi there! I ran into a few issues where my bot's view of group membership would start to fall out of sync with reality. Adding/removing the bot from the group didn't fix things. I was able to find that there was a signal-cli command to re-sync the group state [here](https://github.com/AsamK/signal-cli/issues/1095#issuecomment-1309019924), but there didn't appear to be a way to trigger that from signal-cli-rest-api.
So, I just added a new endpoint `POST /v1/groups/{number}/{groupid}/refresh` that calls the appropriate refresh command. Can confirm that it works and helped solve some long-standing issues with my bots :)
Thanks for building and maintaining this project! It's been incredibly useful.
=> Add the ability to refresh a group.

src/api/api.go, src/client/client.go, src/docs/swagger.yaml
`signal-cli` allows for updating the group name along with description and avatar
https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#updategroup
this PR adds that functionality to signal-cli-rest-api
=> Allow updating group name

src/client/client.go, src/client/jsonrpc2.go
This PR adds the link-device functionality previously available in `native` to `json-rpc`. As signal-cli requires there to be a second request `finishLink` sent to actually link the device, this runs in a goroutine after the qr code is sent. The goroutine either finishes successfully, or dies after 1 minute due to signal-cli sending a failure message. (the result is available through debug logs).
To accomplish this, the `receivedMessages` chan had to be modified to actually be a map from "message id" (generated by us) to chan, indexed by the message receiver goroutine when a message is received and deleted after the result is parsed. 
This is because when there was an ongoing `finishLink` "job" running, the chan listener would eat all the other responses, so the service locked up while …
=> Link device in JSON-RPC mode

src/api/api.go, src/client/client.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/main.go
Adds `GET /v1/accounts` which returns an array of phone numbers (accounts) available to use.
[The main signal-cli manpage](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc) does not reference this functionality, but [the manpage for the dbus API](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli-dbus.5.adoc#signalcontrol-interface) does:
```
listAccounts() → accountList<as>
accountList : Array of all attached accounts in DBus object path form
```
Tested with both json-rpc and native mode, confirmed to show linked accounts, I sadly can't test it with number registrations, so it would be nice if somebody could confirm it works!
Also, I noticed that when running `swag i` on the latest version of swaggo, there are **a lot** of additional changes to the …
=> Get list of accounts

entrypoint.sh
=> Pass JAVA_OPTS through to signal-cli in json-rpc mode

src/api/api.go, src/client/client.go, src/main.go
Adds support for [sending read receipts](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#receive) on receive.
Closes #431
=> Add support for read receipts on /receive

src/api/api.go, src/client/client.go, src/main.go
Added `POST /v1/receipt/{number}` endpoint to support read receipts for individual messages, as opposed to all received as currently exists with `/receive`. Complements functionality raised in #431 and #524.
Accepts a payload like:
```
{
"receipt_type": "read",
"recipient": "+12345678900",
"timestamp": 1715386986897
}
```
=> Add endpoint support for individual read receipts

README.md
I wrote a utility script over at [signal-cli-to-file](https://github.com/jneidel/signal-cli-to-file) that receives incoming messages from signal-cli-rest-api and save them as files.
It's required for my basic use case for signal-cli:
> My use case is to write notes on my phone, take pictures or record audios that then just show up in my note-taking system. All very convieniently through signal.
Linking to it here so other people don't have to recreate it :smile:
=> Add a link to signal-cli-to-file

src/api/api.go, src/client/client.go, src/main.go
We are having this issue https://github.com/bbernhard/signal-cli-rest-api/issues/546 recently where we no longer receive the phone numbers in the signal-cli payload.
We are looking to adapt how we handle our onboarding. If a message is sent out to a username instead of a phone number, a contact is added, which includes the uuid and if we expose the `listContacts` command, we can save the uuid so that when we receive a message, we will be able to correctly identify the person.
=> Expose listContacts endpoint

README.md, src/main.go
I ran into the issue that I could not easily test this service behind a reverse proxy, because of the hard-coded `IP:PORT` set up. This should fix that. Please let me know if you need any other related changes before this can be accepted.
Changes:
- Add `SWAGGER_HOST` environment variable to `README.md` for Swagger UI configuration.
- Update `main.go` to use `SWAGGER_HOST` environment variable for Swagger UI host configuration.
=> For reverse proxies, add SWAGGER_HOST environment variable support

src/api/api.go, src/client/client.go, src/datastructs/datastructs.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml
Will allow you to send the `notify_self` property to the `/v2/send` endpoint. Leaving the field `null` or setting it to `true` will cause the current default behavior and should therefore be backwards compatible.
Setting it to `false` will prevent your devices from generating a notification when you send a message yourself.
The `notify_self` property controls whether the `--notify-self` flag is attached to the generated command (which currently is always the case).
Useful when you are using the API for both messages that you want to be notified about (for example when your home assistant sends out an alert) and ones you don't need to be alerted to (when using from a chat application where you compose messages yourself).
I have tried to autogenerate the documentation using swaggo/swag with …
=> Add support to disable notify-self flag on /v2/send endpoint

src/api/api.go, src/client/client.go
@bbernhard We wanted to add the about text to the UpdateProfileRequest to be able to set this via signal-cli-rest-api.
I built the image and tested this with the about text and without and it seems to work on my end.
=> Add ability to update about text in UpdateProfileRequest

src/api/api.go
I've generated a Java SDK for the signal-cli-rest-api with liblab. They parse their URL arguments with `URLEncoder.encode(value, StandardCharsets.UTF_8.toString());`, which turns `+1234` into `%2B1234`. Thus, when I use the client to query the API, I get a 400 error because `/v1/groups/%2B1234` is malformed.
Escape the number when parsing it.
I have never written Go code before, so feel free to point out any problems here!
Googling, it seems like `+` is actually allowed in part of the URL - it must be escaped if following a `?`, and can be escaped before. So it seems reasonable to handle both ways.
=> Handle phone numbers that start with "%2B"

src/api/api.go, src/docs/README.md, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/main.go
I use liblab to generate SDK clients from swagger. It complained about a few things that I had to fix. Some seemed like legitimate bugs, others I just added some placeholders.
1. Reaction and receipt endpoints were missing descriptions for their path parameters
2. Search endpoint had a description for its path parameter, but path parameter was not present in path
3. Host and scheme were missing (not sure if they are genuinely required in the spec but Liblab won't generate an SDK without them so hoping we can get them in too!)
=> Swagger fixes

src/client/client.go
Relates to #573, unfortunately I forgot to add the flag for the json-rpc mode which this PR will do. Should work the same, if the flag is not set, it should enable the self-notification by default so it is consistent with the existing behavior.
=> Add notify-self-flag support for json-rpc mode

src/api/api.go
editor.swagger.io reports this error with the swagger.yml:
```
Structural error at paths./v1/search/{number}.get.parameters.0
should have required property 'required'
missingProperty: required
```
Set the `required` parameter to `true` for the `/v1/search` endpoint.
I tried to regenerate all the docs but get a bunch of other unnecessary changes so I'll leave that up to you @bbernhard - sorry!
=> Path parameter in /v1/search is required

README.md
I added Secured-Signal-API to the `#client-libraries-and-scripts` Section.
=> Add Secured-Signal-API to Third Party Apps
